let data = [
  {
    id: 1,
    name: "girish chaudhari",
    email: "girish@gmail.com",
    mobile: "9021929562",
    project: "OTM",
    task: "admin panel",
    status: "progress",
    start_time: "2022-03-11",
    end_time: "2022-03-12",
  },
  {
    id: 2,
    name: "vinay chaudhari",
    email: "vinay@gmail.com",
    mobile: "9021929562",
    project: "FACEBOOK",
    task: "admin panel",
    status: "done",
    start_time: "2022-02-10",
    end_time: "2022-02-20",
  },
  {
    id: 3,
    name: "sagar bhai",
    email: "girish@gmail.com",
    mobile: "9021929562",
    project: "INSTA PANEL",
    task: "admin panel",
    status: "planned",
    start_time: "2022-04-05",
    end_time: "2022-04-12",
  },
  {
    id: 4,
    name: "dummy jenil",
    email: "sunil@gmail.com",
    mobile: "9021929562",
    project: "OTM VENDOR",
    task: "admin panel",
    status: "planned",
    start_time: "2022-04-15",
    end_time: "2022-04-25",
  },
];

const searchShopData = [
  {
    name: "Football",
    price: "$38",
    qty: 25,
    category: "sporting",
    cart: false,
  },
  {
    name: "Baseball",
    price: "$35",
    qty: 23,
    category: "sporting",
  },
  {
    name: "Basketball",
    price: "$40",
    qty: 0,
    category: "sporting",
    cart: false,
  },
  {
    name: "Ipad",
    price: "$8320",
    qty: 23,
    category: "electronics",
    cart: false,
  },
  {
    name: "Nexus 7",
    price: "$5609",
    qty: 42,
    category: "electronics",
    cart: false,
  },
  {
    name: "Iphone 5",
    price: "$6609",
    qty: 0,
    category: "electronics",
  },
  {
    name: "Rings",
    price: "$349",
    qty: 0,
    category: "jwellery",
  },
  {
    name: "Neck pieces",
    price: "$609",
    qty: 5,
    category: "jwellery",
  },
  {
    name: "Ear rings",
    price: "$1209",
    qty: 10,
    category: "jwellery",
  },
];

export { data, searchShopData };
